"""
Turns an arrangement entered in the questionnaire into the ALT/ALT press pieces needed to remove and install its
bearings, and the pieces of all arrangements into one cart.

The rules themselves are data (data/rules/rules.json, generated by data/rules/build_rules.py); this module only
applies them: it picks the rule set for the arrangement, the jobs to do, the option of each job that the answers
select, and the size and catalogue entry of every piece. Anything it cannot decide is returned as unresolved,
with the reason, for a person to complete.
"""
import json
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional, Tuple

ROOT = Path(__file__).resolve().parents[3]
RULES = json.loads((ROOT / "data/rules/rules.json").read_text())
_CATALOG = json.loads((ROOT / "data/altalt_site/catalog.json").read_text())

RULE_SETS = {a["id"]: a for a in RULES["arrangements"]}
AVAILABLE = RULES["available_sizes"]
PIECE_NAMES = RULES["pieces"]

# pieces sold in acetal and in aluminium: acetal is kind to carbon, aluminium is the sturdier choice otherwise
HAS_MATERIAL = {"drift_re", "pilot_short", "pilot_long", "sleeve", "sleeve_long", "step", "spacer_tube"}
# leverage pieces that only make sense on a hub; on a frame the same job uses Step + Sleeve
HUB_ONLY = {"sleeve_6", "sleeve_long", "stop_oal"}
IN_HAND = "choose with the part in hand"


# ---------------------------------------------------------------------------------------------------
# Input
# ---------------------------------------------------------------------------------------------------
@dataclass
class BearingSpec:
    code: str
    inner: Optional[float] = None
    outer: Optional[float] = None
    width: Optional[float] = None


@dataclass
class ArrangementSpec:
    """One arrangement as answered in the questionnaire. `slots` lists the bearings per seat, deepest first."""
    name: str
    type: str                                   # SP | BSB | OA
    component: str                              # frame | hub | freehub
    material: str                               # carbon | alloy
    slots: List[List[BearingSpec]] = field(default_factory=list)
    has_center_lock: Optional[bool] = None      # hub
    freehub_body: Optional[str] = None          # hg_microspline | xd_xdr
    freehub_one_side: Optional[bool] = None
    has_spacer: Optional[bool] = None           # BSB
    spacer_len_ge_10mm: Optional[bool] = None
    spacer_mobility: Optional[str] = None       # moves | stuck
    axle_length: Optional[str] = None           # OA: short | long


# ---------------------------------------------------------------------------------------------------
# Catalogue: (piece, size, material) -> the product variant that is sold
# ---------------------------------------------------------------------------------------------------
_VARIANT_PATTERNS = [
    (r"DRIFT RE (\d+) (Acetal|Aluminum)", lambda m: ("drift_re", m[1], m[2])),
    (r"PILOT (\d+) Short (Acetal|Aluminum)", lambda m: ("pilot_short", m[1], m[2])),
    (r"PILOT (\d+) Long (Acetal|Aluminum)", lambda m: ("pilot_long", m[1], m[2])),
    (r"SLEEVE (\d\d) (Acetal|Aluminum)", lambda m: ("sleeve", m[1], m[2])),
    (r"SLEEVE Long (Acetal|Aluminum)", lambda m: ("sleeve_long", None, m[1])),
    (r"SLEEVE 6", lambda m: ("sleeve_6", None, None)),
    (r"Step M8 (Acetal|Aluminum)", lambda m: ("step", None, m[1])),
    (r"Spacer Tube (Acetal|Aluminum)", lambda m: ("spacer_tube", None, m[1])),
    (r"ALT Rod", lambda m: ("alt_rod", None, None)),
    (r"ALT Drift (\d+)", lambda m: ("alt_drift", m[1], None)),
    (r"ALT EXT Single (\d+)", lambda m: ("alt_extractor", m[1], None)),   # the current version, not the "OG" one
    (r"OA Drift (\d+x\d+) Acetal", lambda m: ("oa_drift", m[1], None)),
    (r"Stud M8x(\d+)", lambda m: ("stud", m[1], None)),
    (r"(Dry Hero Dirt|Sand du jour|Organic Cardboard)", lambda m: ("handle", m[1], None)),
]
_SINGLE_PRODUCTS = {"Standard Nut - Pieces": "nut", "Stop CTR - Piece": "stop_ctr", "Stop OAL - Piece": "stop_oal",
                    "O-Ring 8mm": "o_ring", "Stud Stop": "stud_stop"}


def _display_name(piece: str, size: Optional[str], material: Optional[str]) -> str:
    return PIECE_NAMES[piece] + (f" {size}" if size else "") + (f" {material}" if material else "")


def _build_catalog() -> Dict[Tuple[str, Optional[str], Optional[str]], dict]:
    index = {}

    def add(key, variant, label):
        index[key] = {"sku": variant["sku"], "product": label, "unit_price": variant["price_cad"],
                      "piece": key[0], "name": _display_name(*key)}

    for product in _CATALOG["products"]:
        if product["title"] in _SINGLE_PRODUCTS:
            add((_SINGLE_PRODUCTS[product["title"]], None, None), product["variants"][0], product["title"])
            continue
        for v in product["variants"]:
            label = " ".join(v["attributes"].values())
            for pattern, key in _VARIANT_PATTERNS:
                m = re.fullmatch(pattern, label)
                if m:
                    add(key(m), v, label)
                    break
    index[("handle", None, None)] = index[("handle", "Dry Hero Dirt", None)]     # the colour used unless another is picked
    return index


CATALOG = _build_catalog()
BY_SKU = {entry["sku"]: entry for entry in CATALOG.values()}


def catalog_items() -> List[dict]:
    """Every individual piece that can be put in a cart, for the pickers of the cart editor."""
    return sorted(({"sku": e["sku"], "name": e["name"], "piece": e["piece"], "unit_price": e["unit_price"]}
                   for e in BY_SKU.values()), key=lambda e: (e["piece"], e["name"]))


# ---------------------------------------------------------------------------------------------------
# Which rule set, which jobs
# ---------------------------------------------------------------------------------------------------
def rule_set_for(spec: ArrangementSpec) -> Tuple[str, List[str]]:
    """The rule set (one of the ten arrangements of rules.json) that the answers describe, and what was assumed."""
    assumed = []
    if spec.type == "SP":
        stacked = bool(spec.slots) and len(spec.slots[0]) > 1
        return ("double_stacked_pivot" if stacked else "simple_pivot"), assumed
    if spec.type == "OA":
        if spec.axle_length is None:
            assumed.append("Axle length not answered: assumed long (the axle sticks out of the bearings).")
        return ("over_axle_short" if spec.axle_length == "short" else "over_axle"), assumed
    # BSB
    if spec.component == "freehub":
        if spec.freehub_one_side is None:
            assumed.append("Not answered whether both bearings go in from the same side: assumed one from each side.")
        return ("bsb_freehub_one_side" if spec.freehub_one_side else "bsb_freehub"), assumed
    if spec.component == "hub":
        return ("bsb_hub_no_spacer" if spec.has_spacer is False else "bsb_hub"), assumed
    if spec.has_spacer is False:
        assumed.append("A frame BSB without a spacer has no rule set of its own: treated as a thin-spacer BSB pivot.")
        return "bsb_pivot", assumed
    return ("bsb_frame" if spec.spacer_len_ge_10mm else "bsb_pivot"), assumed


def _uses_alt_drift(spec: ArrangementSpec, rule_id: str, bearing: Optional[BearingSpec], assumed: List[str]) -> bool:
    """The first bearing of a pair comes out with the ALT Drift only inside its limits; otherwise the ALT Extractor."""
    if bearing is None or bearing.inner not in AVAILABLE["alt_drift"]:
        return False
    if rule_id == "bsb_hub_no_spacer":
        return True
    if not (spec.has_spacer and spec.spacer_len_ge_10mm):
        return False
    if spec.spacer_mobility is None:
        assumed.append("Not answered whether the spacer moves: the ALT Extractor is used, since it works either way.")
    return spec.spacer_mobility == "moves"


def _plan(spec: ArrangementSpec, rule_id: str, assumed: List[str]) -> List[Tuple[str, int, int]]:
    """The jobs to do, in order: (operation id in the rule set, slot of the bearing worked on, position in its stack)."""
    if rule_id == "simple_pivot":
        return [("remove", 0, 0), ("install", 0, 0)]
    if rule_id == "double_stacked_pivot":
        return [("remove_1st_extractor", 0, 1), ("2nd_remove", 0, 0), ("1st_install", 0, 0), ("2nd_install", 0, 1)]

    sided = rule_id in ("bsb_hub", "bsb_hub_no_spacer", "over_axle", "over_axle_short")
    # with both bearings going in from the outboard end, the outboard one comes out first and goes in last
    first_out = 1 if rule_id == "bsb_freehub_one_side" else 0
    first_in = 0
    ids = RULE_SETS[rule_id]["operations"]
    has = lambda op_id: any(o["id"] == op_id for o in ids)

    def op_id(base: str, slot: int) -> str:
        with_side = f"{base}_{'disc' if slot == 0 else 'drive'}"
        return with_side if sided and has(with_side) else base

    first_bearing = _bearing(spec, first_out, 0)
    remove_first = "remove_1st"
    if rule_id not in ("over_axle", "over_axle_short"):
        drift_exists = has(op_id("remove_1st", first_out))
        if not (drift_exists and _uses_alt_drift(spec, rule_id, first_bearing, assumed)):
            remove_first = "remove_1st_extractor"

    removal = [(op_id(remove_first, first_out), first_out), (op_id("remove_2nd", 1 - first_out), 1 - first_out)]
    install = [(op_id("install_1st", first_in), first_in), (op_id("install_2nd", 1 - first_in), 1 - first_in)]

    plan: List[Tuple[str, int, int]] = []
    for op, slot in removal:
        if len(spec.slots[slot]) > 1:
            plan.append(("stacked_remove", slot, 1))      # the outer bearing of a stacked seat comes out first
        plan.append((op, slot, 0))
    for op, slot in install:
        plan.append((op, slot, 0))
        if len(spec.slots[slot]) > 1:
            plan.append(("stacked_install", slot, 1))     # and goes in last
    return plan


def _bearing(spec: ArrangementSpec, slot: int, position: int) -> Optional[BearingSpec]:
    try:
        return spec.slots[slot][position]
    except IndexError:
        return None


# ---------------------------------------------------------------------------------------------------
# Picking options and sizes
# ---------------------------------------------------------------------------------------------------
def _condition(cond: Optional[str], spec: ArrangementSpec) -> Optional[bool]:
    """True / False, or None when the answer that decides it was left blank."""
    if cond in ("six_bolt", "center_lock"):
        if spec.component != "hub":
            return False
        if spec.has_center_lock is None:
            return None
        return spec.has_center_lock == (cond == "center_lock")
    if cond in ("hg", "xd"):
        if spec.component != "freehub":
            return False
        if spec.freehub_body is None:
            return None
        return spec.freehub_body == ("hg_microspline" if cond == "hg" else "xd_xdr")
    if cond == "frame":
        return spec.component == "frame"
    return False     # "default" and "manual" are handled by the caller


def _pick(options: List[dict], spec: ArrangementSpec, operation: str, assumed: List[str], notes: List[str]) -> Tuple[List[dict], List[str]]:
    """The pieces of the option that applies, and the other options described for a person to consider."""
    if not options:
        return [], []
    chosen = None
    if len(options) == 1 and options[0]["cond"] in (None, "default"):
        chosen = options[0]
    if chosen is None:
        results = [(o, _condition(o["cond"], spec)) for o in options if o["cond"] not in ("default", "manual", None)]
        chosen = next((o for o, r in results if r is True), None)
        if chosen is None:
            chosen = next((o for o in options if o["cond"] in ("default", None)), None)
        if chosen is None:
            unknown = next((o for o, r in results if r is None), None)
            if unknown is not None:
                chosen = unknown
                assumed.append(f"A question that decides the leverage piece was left blank: assumed '{unknown['when']}'.")
    pieces = list(chosen["pieces"]) if chosen else None

    # hub leverage pieces have nothing to rest on when the part is a frame
    if spec.component == "frame" and (pieces is None or any(p["piece"] in HUB_ONLY for p in pieces)):
        # on removal the sleeve receives the bearing being pushed out; on install it sits around the other seat
        around = "od" if operation == "remove" else "od_other"
        pieces = [{"piece": "step", "qty": 1}, {"piece": "sleeve", "qty": 1, "size": around}]
        notes.append("The rule names a hub leverage piece; on a frame, Step + Sleeve is used instead.")
        chosen = None
    if pieces is None:
        pieces = []
        notes.append("No leverage option fits this component: choose the leverage piece by hand.")

    alternatives = [
        f"{' + '.join(PIECE_NAMES[p['piece']] for p in o['pieces']) or 'nothing'}: {o['when']}"
        for o in options if o is not chosen and o["cond"] == "manual"
    ]
    return pieces, alternatives


def _fmt(x: float) -> str:
    return str(int(x)) if float(x).is_integer() else str(x)


def _size(piece: str, rule: Optional[str], bearing: Optional[BearingSpec], other: Optional[BearingSpec]) -> Tuple[Optional[str], Optional[str]]:
    """(size, note). A size of None with a note means a person has to choose it."""
    if rule is None:
        return (None, f"length: {IN_HAND}") if piece == "stud" else (None, None)
    if rule in ("axle_id", ">axle_id", "axle_end"):
        return None, f"{RULES['size_rules'][rule]}: {IN_HAND}"

    target = other if rule in ("od_other", "fits_bore") else bearing
    if target is None:
        return None, "no bearing selected for this seat"
    if target.inner is None or target.outer is None:
        return None, f"dimensions of {target.code} are not known"
    inner, outer = float(target.inner), float(target.outer)
    sizes = AVAILABLE.get(piece, [])

    if piece == "oa_drift":
        # the drift slides over the axle, whose outside is the bearing's inside unless the axle is stepped
        wanted = f"{_fmt(inner)}x{_fmt(outer)}"
        if rule == "od":
            match = next((s for s in sizes if s.endswith(f"x{_fmt(outer)}")), None)
            return (match, "any inner size works here") if match else (None, f"no Over Axle Drift for OD {_fmt(outer)}")
        if wanted in sizes:
            return wanted, "sized from the bearing: check the axle is not thinner where the drift slides"
        return None, f"no Over Axle Drift {wanted}: {IN_HAND}"

    if rule in ("od", "od_other"):
        if piece == "sleeve":
            match = next((s for s in sizes if s >= outer), None)
            note = None if match == outer else f"no Sleeve for OD {_fmt(outer)}: next size up"
            return (_fmt(match), note) if match else (None, f"no Sleeve clears OD {_fmt(outer)}")
        return (_fmt(outer), None) if outer in sizes else (None, f"no {PIECE_NAMES[piece]} for OD {_fmt(outer)}")
    if rule == ">id":
        match = next((s for s in sizes if s > inner), None)
        if match is None or match >= outer:
            return None, f"no Drift RE between ID {_fmt(inner)} and OD {_fmt(outer)}"
        return _fmt(match), None
    if rule == ">seat":
        match = next((s for s in sizes if s > outer), None)
        return (_fmt(match), None) if match else (None, f"no Drift RE larger than OD {_fmt(outer)}")
    if rule == "id":
        return (_fmt(inner), None) if inner in sizes else (None, f"no {PIECE_NAMES[piece]} for ID {_fmt(inner)}")
    return None, f"unknown size rule {rule}"


def _line(p: dict, role: str, spec: ArrangementSpec, bearing: Optional[BearingSpec], other: Optional[BearingSpec]) -> Optional[dict]:
    piece = p["piece"]
    # the Stud itself centres the tool in an 8 or 9 mm bore
    if piece in ("pilot_short", "pilot_long") and p.get("size") == "id" and bearing and bearing.inner in (8, 9):
        return None
    size, note = _size(piece, p.get("size"), bearing, other)
    needs_size = p.get("size") is not None or piece == "stud"
    resolved = not (needs_size and size is None)

    material = None
    entry = None
    if resolved:
        if piece in HAS_MATERIAL:
            material = "Acetal" if spec.material == "carbon" else "Aluminum"
            entry = CATALOG.get((piece, size, material))
            if entry is None:      # a few sizes exist in one material only
                material = "Aluminum" if material == "Acetal" else "Acetal"
                entry = CATALOG.get((piece, size, material))
        else:
            entry = CATALOG.get((piece, size, None))
        if entry is None:
            resolved, note = False, "not found in the catalogue"

    name = _display_name(piece, size, material if entry else None)
    return {
        "piece": piece, "name": name, "role": role, "qty": p.get("qty", 1),
        "size": size, "material": material if entry else None,
        "sku": entry["sku"] if entry else None, "product": entry["product"] if entry else None,
        "unit_price": entry["unit_price"] if entry else None,
        "resolved": resolved, "note": note or p.get("note"),
    }


# ---------------------------------------------------------------------------------------------------
# Output
# ---------------------------------------------------------------------------------------------------
def _job(spec: ArrangementSpec, rule_id: str, op_id: str, slot: int, position: int, assumed: List[str]) -> dict:
    bearing = _bearing(spec, slot, position)
    other = _bearing(spec, 1 - slot, 0) if len(spec.slots) > 1 else None

    # the outer bearing of a stacked seat is handled like the outer bearing of a double stacked pivot
    if op_id in ("stacked_remove", "stacked_install"):
        source = {"stacked_remove": "remove_1st_extractor", "stacked_install": "2nd_install"}[op_id]
        op = next(o for o in RULE_SETS["double_stacked_pivot"]["operations"] if o["id"] == source)
        title = ("Remove" if op_id == "stacked_remove" else "Install") + " the outer bearing of the double-stacked seat"
    else:
        op = next(o for o in RULE_SETS[rule_id]["operations"] if o["id"] == op_id)
        title = op["title"]
    if spec.component != "hub":
        for hub_side, side in (("disc side", "side A"), ("drive side", "side B")):
            title = title.replace(f"the {hub_side}", side).replace(hub_side, side)

    notes = list(op["notes"]) + [op["hardware"]["note"]]
    lines, alternatives = [], []
    for role in ("press", "center", "leverage"):
        pieces, alts = _pick(op[role], spec, op["operation"], assumed, notes)
        alternatives += [f"{role}: {a}" for a in alts]
        lines += [_line(p, role, spec, bearing, other) for p in pieces]
    lines += [_line(p, "extra", spec, bearing, other) for p in op["extras"]]
    lines += [_line(p, "hardware", spec, bearing, other) for p in op["hardware"]["pieces"]]

    if bearing and bearing.inner in (8, 9) and any(p["piece"].startswith("pilot") for o in op["center"] for p in o["pieces"]):
        notes.append("No Pilot for this bearing: the Stud itself centres the tool in an 8 or 9 mm bore.")

    lines = [l for l in lines if l is not None]
    stack = _stack(op, lines, spec, bearing, other)
    lines = [l for l in lines if l["piece"] != "nut"]
    for item in stack:
        if item["piece"] in ("handle", "stud_stop"):
            entry = CATALOG[(item["piece"], None, None)]
            lines.append({"piece": item["piece"], "name": PIECE_NAMES[item["piece"]], "role": "hardware", "qty": 1,
                          "size": None, "material": None, "sku": entry["sku"], "product": entry["product"],
                          "unit_price": entry["unit_price"], "resolved": True, "note": item["text"]})
    if op["operation"] == "install" and any(l["piece"] == "drift_re" and l["role"] == "press" for l in lines):
        notes.append("Which face of the Drift RE presses follows the manufacturer: the flat side by default, the "
                     "relief side when the bearing has to be slightly loaded.")
    dims = lambda b: None if b is None or b.inner is None else {"inner": b.inner, "outer": b.outer, "width": b.width}
    return {
        "title": title,
        "operation": op["operation"],
        "material": "Acetal" if spec.material == "carbon" else "Aluminum",
        "bearing": bearing.code if bearing else None,
        "bearing_dimensions": dims(bearing),
        "other_dimensions": dims(other),
        "status": op["status"],
        "diagram": op["diagram"],
        "pieces": lines,
        "stack": stack,
        "action": op["action"].replace("into the leverage piece", _receiver(lines)),
        "alternatives": alternatives,
        "notes": notes,
    }


# leverage pieces are listed from the part outwards: the piece that touches the part first, what backs it up after
_TOUCHES_PART = {"sleeve", "sleeve_6", "sleeve_long", "oa_drift", "stop_ctr", "stop_oal"}
_WHERE = {
    "press": "pushes the bearing",
    "center": "inside the bore, on the Stud",
    "leverage": "rests against the part",
    "extra": None,
}
_PIECE_WHERE = {
    "sleeve": "against the part, around the seat; the bearing or axle moves into it",
    "sleeve_6": "against the 6-bolt disc mount; the bearing or axle moves into it",
    "sleeve_long": "on the centre-lock disc mount; the bearing or axle moves into it",
    "step": "closes the open end of the sleeve",
    "stop_ctr": "centres itself in the opening on this side and rests against the part",
    "stop_oal": "rests against the part and clears the end of the axle",
    "spacer_tube": "reaches through the part to the drift",
    "alt_rod": "passes through the other bearing and the spacer, carrying the ALT Drift; "
               "the only part you turn, with an Allen key",
    "alt_extractor": "goes into the bearing and grips it when the bolt in its head is tightened with an Allen key; "
                     "its stud points out through the sleeve",
}


def _receiver(lines: List[dict]) -> str:
    """Where the removed bearing ends up, named after the leverage piece actually used."""
    leverage = {l["piece"] for l in lines if l["role"] == "leverage"}
    if leverage & {"sleeve", "sleeve_6", "sleeve_long"}:
        return "into the sleeve"
    if "stop_oal" in leverage:
        return "into the Stop OAL"
    return "towards the leverage drift at the other end"


def _stack(op: dict, lines: List[dict], spec: ArrangementSpec, bearing: Optional[BearingSpec],
           other: Optional[BearingSpec]) -> List[dict]:
    """What sits on the Stud, in order from the pressing end to the leverage end, each with its place in words."""
    remaining = [{**l} for l in lines]

    def take(role: str, piece: Optional[str] = None) -> List[dict]:
        found = [l for l in remaining if l["role"] == role and l["qty"] > 0 and (piece is None or l["piece"] == piece)]
        if piece is not None:
            found = found[:1]
        for l in found:
            l["qty"] -= 1
        return found

    def entry(line: dict) -> dict:
        where = line["note"] if line["resolved"] and line["note"] else _PIECE_WHERE.get(line["piece"]) or _WHERE[line["role"]]
        if spec.component != "hub":      # the rules shared with hubs speak of disc and drive sides
            for hub_word, word in (("disc-side", "side A"), ("drive-side", "side B"), ("the disc side", "side A"),
                                   ("the drive side", "side B"), ("the hub", "the part")):
                where = where.replace(hub_word, word)
        return {"kind": "piece", "piece": line["piece"], "role": line["role"], "size": line["size"],
                "material": line["material"], "name": line["name"], "resolved": line["resolved"],
                "text": where if line["resolved"] else f"size not set ({line['note']})"}

    code = lambda b: b.code if b else "not selected"
    workpiece = {
        "bearing": f"the new bearing ({code(bearing)})",
        "bearing_in_part": f"the bearing to remove ({code(bearing)}), in its seat",
        "other_bearing": f"the bearing in the other seat ({code(other)})",
        "spacer": "the spacer between the two bearings",
        "axle": "the axle, inside the part",
        "part": "the part, with the empty seat towards the bearing",
        "bore": "the empty bearing seat on the far side",
    }
    # shown as a Handle on the end that is turned and a Stud Stop on the other; a Standard Nut does either job
    HANDLE, STOP = ("handle", "Handle (or a Standard Nut)"), ("stud_stop", "Stud Stop (or a Standard Nut)")
    fasteners = [t for t in op["stack"] if t.startswith("nut")]

    def fastener(token: str, first: bool) -> Tuple[Tuple[str, str], str]:
        if token == "nut:hold":
            return STOP, "hold it still, do not turn it"
        if token == "nut:pull":
            return STOP, "at the back, on the extractor's stud, where it acts as the nut"
        if first:
            return HANDLE, "turn this end to tighten" + (" (a Stud Stop does not suit this end)" if token == "nut:plain" else "")
        return STOP, "holds the other end; it needs a piece larger than 20 mm to sit against"

    stack = []
    for token in op["stack"]:
        if token.startswith("nut"):
            (key, name), text = fastener(token, first=token is fasteners[0] and not any(x["role"] == "hardware" for x in stack))
            stack.append({"kind": "piece", "piece": key, "role": "hardware", "size": None, "material": None,
                          "name": name, "resolved": True, "text": text})
        elif token in workpiece:
            if token == "spacer" and spec.has_spacer is False:
                continue
            stack.append({"kind": "workpiece", "piece": token, "role": None, "size": None, "material": None,
                          "name": workpiece[token], "resolved": True, "text": None})
        elif token == "leverage":
            found = take("leverage")
            found.sort(key=lambda l: l["piece"] not in _TOUCHES_PART)
            stack += [entry(l) for l in found]
        else:
            role, piece = token.split(":")
            stack += [entry(l) for l in take(role, piece)]
    return stack


def instructions_for(result: dict) -> str:
    """The jobs of one arrangement as plain text a mechanic can follow."""
    out = [f"{result['arrangement'].upper()}  ({result['rule_set_name']})", ""]
    for a in result["assumptions"]:
        out.append(f"Assumed: {a}")
    if result["assumptions"]:
        out.append("")
    for n, job in enumerate(result["jobs"], 1):
        uses_stud = any(l["piece"] == "stud" for l in job["pieces"])
        out.append(f"{n}. {job['title']}" + (f": {job['bearing']}" if job["bearing"] else ""))
        out.append("   Put these on the Stud in this order, from one end to the other:" if uses_stud
                   else "   Assemble in this order:")
        for k, item in enumerate(job["stack"], 1):
            mark = "" if item["resolved"] else "  <-- TO CHOOSE"
            text = f": {item['text']}" if item["text"] else ""
            out.append(f"     {chr(96 + k)}. {'[' + item['name'] + ']' if item['kind'] == 'workpiece' else item['name']}{text}{mark}")
        o_rings = sum(l["qty"] for l in job["pieces"] if l["piece"] == "o_ring")
        if o_rings:
            out.append(f"   Use {o_rings} O-ring{'s' if o_rings > 1 else ''} on the Stud to keep the pilot{'s' if o_rings > 1 else ''} from sliding.")
        if uses_stud:
            out.append("   Stud length: choose with the part in hand.")
        out.append(f"   Then: {job['action']}")
        for alt in job["alternatives"]:
            out.append(f"   Alternative for the {alt}")
        for note in job["notes"]:
            out.append(f"   Note: {note}")
        if job["status"] != "diagram":
            out.append("   (No official diagram for this job.)")
        elif job["diagram"]:
            out.append(f"   Official diagram: {job['diagram']}")
        out.append("")
    return "\n".join(out)


def tools_for(spec: ArrangementSpec) -> dict:
    """Every job needed to remove and install the bearings of one arrangement, with the pieces of each job."""
    rule_id, assumed = rule_set_for(spec)
    expected = 1 if spec.type == "SP" else 2
    slots = (spec.slots + [[] for _ in range(expected)])[:expected]
    spec = ArrangementSpec(**{**spec.__dict__, "slots": slots})

    jobs = [_job(spec, rule_id, op_id, slot, position, assumed) for op_id, slot, position in _plan(spec, rule_id, assumed)]
    return {
        "arrangement": spec.name,
        "rule_set": rule_id,
        "rule_set_name": RULE_SETS[rule_id]["name"],
        "assumptions": list(dict.fromkeys(assumed)),
        "jobs": jobs,
    }


def cart_for(results: List[dict]) -> dict:
    """
    The pieces to buy for all the given arrangements. Press pieces are reused from one job to the next, so the
    quantity of a piece is the most that any single job needs, not the sum over jobs.
    """
    items: Dict[str, dict] = {}
    unresolved: Dict[Tuple[str, Optional[str]], dict] = {}
    for result in results:
        for job in result["jobs"]:
            # a job can use the same piece twice (one Drift RE to press, another to leverage): add those up first
            in_job: Dict[tuple, dict] = {}
            for line in job["pieces"]:
                key = ("sku", line["sku"]) if line["resolved"] else ("open", line["name"], line["note"])
                entry = in_job.setdefault(key, {**line, "qty": 0})
                entry["qty"] += line["qty"]
            for key, line in in_job.items():
                if line["resolved"]:
                    item = items.setdefault(line["sku"], {"key": line["sku"], "sku": line["sku"], "piece": line["piece"],
                                                          "name": line["name"], "unit_price": line["unit_price"], "qty": 0})
                else:
                    item = unresolved.setdefault(key[1:], {"key": f"open:{line['name']}|{line['note']}", "sku": None,
                                                           "piece": line["piece"], "name": line["name"],
                                                           "reason": line["note"], "qty": 0})
                item["qty"] = max(item["qty"], line["qty"])
    lines = sorted(items.values(), key=lambda i: i["name"])
    return {
        "currency": _CATALOG["currency"],
        "items": lines,
        "unresolved": list(unresolved.values()),
        "total": round(sum(i["qty"] * i["unit_price"] for i in lines), 2),
    }


def apply_cart_edits(cart: dict, edits: List[dict]) -> dict:
    """
    The cart as the person wants it: the computed lines with their changes (another size, another quantity,
    removed, or a size chosen for a piece the rules left open), plus the pieces added by hand.

    :param edits: [{"key": key of a computed line or "added:<sku>", "sku": chosen sku or None, "qty": int}]
    """
    by_key = {e["key"]: e for e in edits}
    lines = []
    for base in cart["items"] + cart["unresolved"]:
        edit = by_key.pop(base["key"], None)
        sku = (edit and edit["sku"]) or base["sku"]
        entry = BY_SKU.get(sku)
        qty = edit["qty"] if edit else base["qty"]
        lines.append({
            "key": base["key"], "piece": base["piece"], "sku": sku,
            "name": entry["name"] if entry else base["name"],
            "qty": qty, "unit_price": entry["unit_price"] if entry else None,
            "origin": "rule", "edited": edit is not None, "removed": qty == 0,
            "reason": None if entry else base.get("reason"),
        })
    for key, edit in by_key.items():
        entry = BY_SKU.get(edit["sku"])
        if key.startswith("added:") and entry:      # edits of lines the rules no longer produce are ignored
            lines.append({"key": key, "piece": entry["piece"], "sku": entry["sku"], "name": entry["name"],
                          "qty": edit["qty"], "unit_price": entry["unit_price"], "origin": "added", "edited": True,
                          "removed": False, "reason": None})
    total = sum(l["qty"] * l["unit_price"] for l in lines if l["unit_price"] is not None and not l["removed"])
    return {"currency": cart["currency"], "lines": lines, "total": round(total, 2)}
